#!/bin/bash
source /usr/lib/openfoam/openfoam2512/etc/bashrc

echo -e "\nSTART AT:" $(date +%d\ %h\ %Y,\ %H:%M:%S) "\n"


# ==================== CORES LOADING ===========================
# load np directly from initialConditions, no need for Processors file
mock="$(grep 'np' initialConditions | awk '{print $2}')"
np=${mock:0:${#mock}-1}
# ================================================================

echo -e "\nPostprocessing:"

echo "	functionObjects"
	mpirun -np $np simpleFoam -postProcess -funcs "(vorticity wallShearStress yPlus)" -latestTime -parallel > log_solve/06_functionObjects
	
#echo "	Lambda2"
#	mpirun -np $np postProcess -func "Lambda2" -latestTime -parallel > log_solve/Lambda2

#echo "	Q"
#	mpirun -np $np postProcess -func "Q" -latestTime -parallel > log_solve/Q

echo "	totalPressureIncompressible"
	mpirun -np $np postProcess -func "totalPressureIncompressible(p,U,rhoInf=1.225)" -latestTime -parallel > log_solve/07_totalPressureIncompressible
	
echo "	mag(vorticity)"
	mpirun -np $np postProcess -func "mag(vorticity)" -latestTime -parallel > log_solve/08_magVorticity
echo -e "  --> Done";

echo -e "\nGenerating controlDict_surfaces"
    python3 postProcessor/generate_surfaces.py
echo "  --> Done";

echo -e "\nsurfaces"
    mpirun -np $np simpleFoam -postProcess -dict system/controlDict_surfaces -latestTime -parallel > log_solve/09_surfaces
echo "  --> Done";

echo -e "\nReconstructing case";
	reconstructPar -latestTime > log_solve/10_reconstructPar
echo "  --> Done";

echo -e "\nReconstructing fields";
	reconstructPar -withZero -fields '(phi)' -latestTime > log_solve/11_reconstructPar0
echo "  --> Done";

mkdir allProcessors

mv processor* ./allProcessors

echo -e "\nEND AT:" $(date +%d\ %h\ %Y,\ %H:%M:%S)
